name: test

on: push

jobs:
  test:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version: [3.9]
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Test
          env:
            NEPTUNE_API_TOKEN: ${{ secrets.E2E_NEPTUNE_API_TOKEN }}
            NEPTUNE_PROJECT: e2e-tests/e2e
          uses: ./.github/actions/e2e
